
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[402] =
    {   0,
        0,    0,    0,    0,    0,    0,   71,   69,   59,   59,
       52,   69,   56,   53,   52,   69,   51,   52,   52,   56,
       52,   51,   53,   42,   43,   54,   50,   53,   55,   53,
       54,   58,   58,   69,   53,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   50,   53,   52,   56,    3,    3,    3,   67,   68,
       59,   53,    0,   49,    0,    0,   56,    0,    0,    0,
        0,   57,   55,   57,    0,    0,   52,   51,    0,   45,
        1,    0,   45,   42,    0,    0,   42,   42,    0,   42,
       43,   43,   43,   43,   50,   53,   53,   58,    0,    0,

       60,    0,    0,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   33,   58,   58,   58,   58,   58,   58,   37,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,    0,    0,    0,    3,    3,    2,   67,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   48,    0,
        0,    0,    0,   54,    0,   45,    0,    4,    0,   46,
       42,   42,   42,   42,    0,   44,   43,   43,   43,   43,
        0,    0,    0,    0,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   35,   58,
       58,   16,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   61,    0,
        0,    0,    0,    0,    0,   45,   46,   42,    0,    0,
       44,    0,   44,   44,   43,    0,    0,    0,    0,   58,
       58,   58,    8,   58,   30,    9,   58,   58,   58,   58,
       34,   12,   58,   58,   36,   58,   17,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   27,
       58,   58,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   44,   44,    0,   47,   44,
       44,    0,    0,    0,    0,    5,   58,   58,   29,   10,

       58,   58,   58,   58,   14,   58,   58,   58,   58,   20,
       58,   58,   58,   58,   58,   58,   25,   58,   58,   41,
        0,    0,    0,    0,    0,   62,    0,    0,   65,    0,
        0,   47,   44,    0,    0,    0,   58,   58,   58,   58,
       58,   11,   13,   15,   58,   58,   38,   21,   39,   22,
       23,   40,   58,   58,   58,    0,    0,    0,    0,    0,
       63,    0,    0,    0,    0,   58,   58,   58,   32,   58,
       58,   24,   58,   58,    0,    0,    0,   64,    0,    0,
        0,    6,   58,   31,   18,   19,   26,   28,    0,    0,
        0,    0,    0,   58,    0,   66,    0,    0,    0,    7,

        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   36,
       33,   33,   33,   33,   37,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    4,    1,    1,    1,    5,    1,    6,    6,
        7,    1,    1,    1,    1,    8,    9,    7,    7,    7,
        7,    7,   10,   10,   10,   10,   11,   11,    1,   11,
        1,    1,   10,    6,    6,    7,    7,    7,    6,   10,
       10,   10,   10,   10,   10,   11,   10,   10,   11,   10,
       11,   11,   11,   10,   11,   10,   10,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[465] =
    {   0,
        0, 1007,   69,   70,   68,   69, 1013, 1015,   74,   77,
      987,   78,   81,   64,   78,  971, 1015,  985,   77, 1015,
       80,   80,   91,  119,  124,  983, 1015,   90,  983,   67,
     1015,  967,  102,  114,  981,   90,   70,   67,  109,  122,
      129,  123,   91,  142,  107,   73,  148,   71,  112,  118,
       83, 1015,  102, 1015,  185, 1002, 1001,  985,    0, 1015,
      193, 1015,  168, 1015,  182,  201, 1015,  954,  150,  952,
      948,  991, 1015, 1015,  183,  197, 1015, 1015,  981,  237,
     1015,  994,  244,  280,  194,  208,  208,  111,  979,  184,
      285,  215,  172,  234, 1015,  970,  969,  953,  199,  234,

     1015,    0,    0,  226,  227,  163,  170,  233,  220,  238,
      247,  269,  250,  254,  267,  190,  268,  273,  249,  952,
      283,  279,  290,  281,  286,  287,  303,  301,  305,  308,
      309,  350,  362,  307,  988,  987, 1015,    0,  352,    0,
        0,    0,  940,  928,  940,  983,  929,  962, 1015,  357,
        0,    0,    0, 1015,  354, 1015,  980, 1015,  359,  363,
      332, 1015,  947,  927,    0,  364,  349, 1015,  945,  925,
        0,    0,    0,    0,  347,  348,  345,  350,  375,  365,
      366,  368,  380,  351,  383,  381,  387,  390,  938,  392,
      393,  937,  397,  398,  399,  400,  402,  401,  403,  404,

      406,  408,  415,  413,  412,  419,  414,  427,  920,  929,
      465,    0,  500,    0,  922,  925,  920,  968, 1015,  922,
      463,    0,  540,    0,  455,  458, 1015, 1015,  436,  444,
      451,  495,  454,  463, 1015,    0,    0,    0,    0,  447,
      452,  483,  929,  201,  928,  927,  457,  482,  464,  484,
      926,  925,  495,  496,  924,  487,  923,  502,  497,  499,
      512,  451,  524,  501,  536,  537,  527,  523,  515,  922,
      535,  550,  907,  560,    0,    0,    0,  904,  956,  909,
      790,  568,    0,    0,    0,  554, 1015,  573,  582,  756,
      736,    0,    0,    0,    0,  748,  555,  559,  747,  743,

      557,  564,  567,  565,  741,  572,  566,  570,  579,  740,
      583,  584,  586,  585,  588,  589,  738,  594,  600,  737,
      709,    0,    0,  717,  753, 1015,  747,  746, 1015,    0,
        0, 1015, 1015,    0,    0,    0,  698,  601,  598,  602,
      604,  661,  660,  658,  603,  607,  657,  655,  654,  653,
      652,  647,  608,  615,  605,  636,    0,  650,  678,  672,
     1015,    0,  648,    0,    0,  620,  622,  621,  511,  627,
      628,  458,  630,  631,  448,    0,  492, 1015,    0,    0,
        0,  416,  632,  353,  284,  255,  150,   85,  672,    0,
        0,    0,    0,  633,  678, 1015,    0,    0,    0,   82,

     1015,  702,  713,  724,  735,  741,  752,  763,  773,  783,
      794,  801,  803,  805,  807,  809,  811,  818,  824,  826,
      828,  830,  832,  834,  836,  838,  840,  842,  844,  846,
      848,  850,  852,  854,  856,  858,  865,  876,  882,  884,
      886,  888,  890,  892,  894,  896,  903,  909,  911,  913,
      915,  917,  919,  926,  932,  934,  936,  938,  940,  942,
      944,  946,  948,  950
    } ;

static yyconst flex_int16_t yy_def[465] =
    {   0,
      401,    1,  402,  402,  403,  403,  401,  401,  401,  401,
      401,  404,  401,  401,  401,  405,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  406,  406,  401,  401,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  401,  401,  401,  401,  407,  407,  401,  408,  401,
      401,  401,  404,  401,  409,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  405,  410,  401,  401,  401,  401,
      401,  411,  401,  401,  401,  401,  401,  401,  412,  401,
      401,  401,  401,  401,  401,  401,  401,  406,  401,  404,

      401,  413,  414,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  401,  401,  401,  407,  407,  401,  408,  404,  415,
      416,  417,  401,  401,  401,  418,  401,  401,  401,  405,
      419,  420,  421,  401,  401,  401,  411,  401,  401,  401,
      401,  401,  401,  401,  422,  412,  401,  401,  401,  401,
      423,  424,  425,  426,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  401,  401,
      404,  427,  404,  428,  401,  401,  401,  418,  401,  401,
      405,  429,  405,  430,  401,  401,  401,  401,  422,  422,
      401,  401,  401,  401,  401,  431,  432,  433,  434,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  401,  404,  435,  213,  436,  401,  437,  401,
      438,  405,  439,  223,  440,  401,  401,  401,  401,  401,
      401,  441,  442,  443,  444,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      401,  445,  446,  401,  437,  401,  447,  438,  401,  448,
      449,  401,  401,  450,  451,  452,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  401,  453,  404,  454,  447,
      401,  455,  405,  456,  457,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  401,  458,  454,  401,  459,  460,
      461,  406,  406,  406,  406,  406,  406,  406,  401,  462,
      463,  464,  444,  406,  401,  401,  446,  449,  451,  406,

        0,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401
    } ;

static yyconst flex_int16_t yy_nxt[1087] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   26,   27,   28,   29,   30,   31,   32,   32,   32,
       32,   32,   32,   32,   33,   32,   32,   32,   17,   34,
       17,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       32,   44,   32,   45,   32,   32,   32,   32,   46,   47,
       48,   49,   50,   51,   32,   32,   32,   52,   53,   17,
       54,   57,   57,   60,   60,   61,   61,   61,   61,   61,
       61,   58,   58,   64,   66,   72,   62,   67,   73,   74,
       77,   62,   97,   60,   60,   77,   79,   95,   80,   80,

       80,   73,   73,   81,   73,   78,   99,  100,   82,   99,
       99,   74,   99,   96,   62,   73,  101,   65,  104,  105,
      123,   99,   99,  106,   99,  108,   73,   68,   69,   99,
       99,  107,   70,  131,   71,   83,  128,   84,   84,   85,
       83,   99,   91,   91,   91,  163,   99,  119,   99,   86,
      102,   99,  109,   87,   86,   88,   89,   99,   92,  110,
       93,   99,   99,  122,  164,  111,   86,  129,   99,  112,
       62,   86,   90,   64,  130,  103,  117,   94,  113,  118,
       88,   99,  114,   89,  115,   93,  132,   99,  133,   99,
      120,   67,  149,  116,   61,   61,   61,  121,  124,  125,

      139,  139,   99,  144,   66,  145,  169,   65,  126,   99,
       83,  127,   85,   85,   85,  150,  150,  177,  140,  141,
      162,  159,   76,  159,   86,  170,  160,  160,  160,   99,
      178,   68,   69,  151,  152,  171,  134,  161,   71,   64,
       99,   86,  161,  142,  162,  162,  141,   68,   69,  167,
      187,  168,   70,  299,   71,   80,   80,   80,  153,   99,
      172,  152,   80,   80,   80,   99,   99,  155,  156,  162,
      168,  156,   99,   65,  155,  156,  168,   99,  156,  180,
      179,  181,  175,  176,  155,  156,   99,  167,   99,   99,
      156,  155,  156,   99,   99,  168,   83,  156,   84,   84,

       85,   83,  182,   91,   91,   91,   99,   99,   99,  190,
       86,  184,   99,  185,   87,   86,   88,  183,   99,   92,
       99,   93,   99,   99,  188,   99,   99,   86,  186,   99,
      200,  189,   86,   90,  193,  198,  191,  197,   94,  194,
       99,   88,   99,  192,   99,  201,   93,   99,   99,  195,
      196,  132,  199,  132,  202,  146,  204,   64,  203,  206,
      208,  207,  210,  132,  205,  133,  149,  225,  162,  225,
      211,  211,  226,  226,  226,  221,  221,  160,  160,  160,
      230,  160,  160,  160,   99,  168,   99,   99,  242,   99,
       99,   65,   99,  162,  227,  250,   76,  227,  231,  232,

      233,  209,  241,  240,   99,   99,  243,   99,   68,   69,
      168,  227,  245,  134,   99,   71,  227,  234,  244,   99,
       99,  232,   99,  249,  246,  233,   99,  247,  248,   99,
      251,   99,   99,  254,  253,  252,   99,   99,   99,   99,
       99,   99,   99,   99,  256,   99,  257,   99,  255,  258,
      263,   99,   99,   99,   99,   99,  262,  271,   99,  259,
      261,  260,  267,  269,  264,  270,   99,  265,  266,  268,
       64,  232,  149,  226,  226,  226,  226,  226,  226,  232,
      272,  282,  282,  274,  274,  286,   99,  287,  290,  156,
       99,   99,  156,  232,  378,  389,   99,   99,  311,  287,

      296,  232,   76,   99,   65,   64,  156,  291,  288,  297,
      288,  156,  287,  289,  289,  289,  286,  300,  276,  276,
      276,   99,   99,   99,  287,  302,   99,  276,  276,  276,
      276,  276,  298,  301,   99,   99,   99,  303,   99,   65,
       99,   99,  306,  276,  276,  276,  276,  276,  276,  149,
       99,   99,  313,  304,   99,  308,  305,  309,  284,  284,
      284,  307,   99,   99,  318,   64,   99,  284,  284,  284,
      284,  284,  310,  316,   99,   99,   99,  149,  317,   76,
      312,  314,  315,  284,  284,  284,  284,  284,  284,   99,
      287,  289,  289,  289,   99,  319,   99,  320,   99,   65,

      289,  289,  289,   99,   99,   99,   99,   76,  338,   99,
      339,   99,  340,  332,  342,  287,  332,  341,   99,  344,
      343,  346,   99,   99,   99,   99,  345,   99,   99,  348,
      332,  350,  349,   99,  347,  332,  353,   99,  352,   99,
       99,   99,   99,   99,   99,  351,   99,   99,  366,  354,
      370,  355,  371,  367,   99,   64,  372,  149,  374,   99,
       99,   99,  373,  368,  369,  383,   99,   99,  384,   99,
       99,   99,   99,  395,  361,  395,  387,  396,  388,  395,
      378,  395,  375,  396,  382,  385,   99,   76,  386,   65,
      394,   99,   99,   99,   99,  396,   99,   99,  400,   99,

       99,  396,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   75,   75,   99,   75,   75,
       75,   75,   75,   75,   75,   75,   98,   98,  329,  361,
       98,   98,  135,  135,  135,  326,  135,  135,  135,  135,
      135,  135,  135,  138,  359,  138,  138,  138,  138,  138,
      356,  138,  138,  138,   63,   63,   99,   99,   63,   99,
       99,   63,   99,   63,   75,   75,   99,   99,   75,  333,
      333,   75,  329,   75,  157,  157,  157,  157,  157,  157,

      157,  157,  157,  157,  157,  166,  166,  166,  173,  173,
      174,  174,  212,  212,  213,  213,  214,  214,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  222,
      222,  223,  223,  224,  224,  229,  229,  236,  236,  237,
      237,  238,  238,  239,  239,  275,  275,  277,  277,  283,
      283,  285,  285,  292,  292,  293,  293,  294,  294,  295,
      295,  322,  322,  323,  323,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  330,  330,  331,
      331,  334,  334,  335,  335,  336,  336,  337,  337,  357,

      357,  358,  358,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  362,  362,  363,  363,  364,  364,
       98,   98,  365,  365,  376,  376,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  379,  379,  380,
      380,  381,  381,  390,  390,  391,  391,  392,  392,  393,
      393,  397,  397,  398,  398,  399,  399,  327,  326,  324,
      321,   99,   99,   99,   99,   99,   99,   99,   99,  281,
      219,  280,  279,  278,  273,  210,   99,   99,  235,  235,
      228,  228,  158,   74,  220,  219,  217,  216,  215,  136,
      136,   99,   99,   73,   73,  165,  158,  154,  148,  147,

      146,  143,  137,  136,  136,   73,   99,   62,   74,   73,
       76,   62,  401,   55,    7,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401
    } ;

static yyconst flex_int16_t yy_chk[1087] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    9,    9,    9,   10,   10,
       10,    3,    4,   12,   13,   14,   15,   13,   14,   14,
       19,   30,   30,    5,    6,   21,   22,   28,   22,   22,

       22,   19,   15,   23,   21,   21,   38,   33,   23,   37,
       48,   28,   46,   28,   28,   23,   34,   12,   36,   36,
       46,  400,   51,   36,  388,   38,   53,   13,   13,   36,
       43,   37,   13,   51,   13,   24,   48,   24,   24,   24,
       25,   33,   25,   25,   25,   88,   45,   43,   39,   24,
       34,   49,   39,   24,   25,   24,   24,   50,   25,   39,
       25,   40,   42,   45,   88,   39,   24,   49,   41,   40,
       53,   25,   24,   63,   50,   34,   42,   25,   40,   42,
       24,   44,   41,   24,   41,   25,   55,   47,   55,  387,
       44,   55,   75,   41,   61,   61,   61,   44,   47,   47,

       65,   65,  106,   69,   66,   69,   93,   63,   47,  107,
       85,   47,   85,   85,   85,   76,   76,  106,   65,   65,
       90,   86,   75,   86,   85,   93,   86,   86,   86,  116,
      107,   55,   55,   76,   76,   99,   55,   90,   55,  100,
      244,   85,   87,   65,   87,   90,   65,   66,   66,   92,
      116,   92,   66,  244,   66,   80,   80,   80,   76,  109,
       99,   76,   83,   83,   83,  104,  105,   80,   80,   87,
       94,   80,  108,  100,   83,   83,   92,  110,   83,  109,
      108,  110,  104,  105,   80,   80,  111,   94,  119,  113,
       80,   83,   83,  114,  386,   94,   84,   83,   84,   84,

       84,   91,  111,   91,   91,   91,  115,  117,  112,  119,
       84,  113,  118,  114,   84,   91,   84,  112,  122,   91,
      124,   91,  121,  385,  117,  125,  126,   84,  115,  123,
      126,  118,   91,   84,  122,  125,  121,  124,   91,  123,
      128,   84,  127,  121,  129,  126,   91,  130,  131,  123,
      123,  132,  125,  132,  127,  134,  129,  139,  128,  130,
      131,  130,  134,  133,  129,  133,  150,  155,  161,  155,
      139,  139,  155,  155,  155,  150,  150,  159,  159,  159,
      166,  160,  160,  160,  177,  167,  175,  176,  177,  178,
      184,  139,  384,  161,  160,  184,  150,  160,  166,  166,

      166,  132,  176,  175,  180,  181,  178,  182,  133,  133,
      167,  160,  180,  133,  179,  133,  160,  166,  179,  183,
      186,  166,  185,  183,  181,  166,  187,  182,  182,  188,
      185,  190,  191,  188,  187,  186,  193,  194,  195,  196,
      198,  197,  199,  200,  191,  201,  193,  202,  190,  194,
      199,  205,  204,  207,  203,  382,  198,  207,  206,  195,
      197,  196,  203,  205,  200,  206,  208,  201,  202,  204,
      211,  229,  221,  225,  225,  225,  226,  226,  226,  230,
      208,  221,  221,  211,  211,  231,  240,  231,  233,  226,
      262,  241,  226,  229,  377,  375,  247,  372,  262,  234,

      240,  230,  221,  249,  211,  213,  226,  233,  232,  241,
      232,  226,  231,  232,  232,  232,  234,  247,  213,  213,
      213,  248,  242,  250,  234,  249,  256,  213,  213,  213,
      213,  213,  242,  248,  253,  254,  259,  250,  260,  213,
      264,  258,  256,  213,  213,  213,  213,  213,  213,  223,
      369,  261,  264,  253,  269,  259,  254,  260,  223,  223,
      223,  258,  268,  263,  269,  274,  267,  223,  223,  223,
      223,  223,  261,  267,  271,  265,  266,  282,  268,  223,
      263,  265,  266,  223,  223,  223,  223,  223,  223,  272,
      286,  288,  288,  288,  297,  271,  301,  272,  298,  274,

      289,  289,  289,  302,  304,  307,  303,  282,  297,  308,
      298,  306,  301,  289,  303,  286,  289,  302,  309,  306,
      304,  308,  311,  312,  314,  313,  307,  315,  316,  311,
      289,  313,  312,  318,  309,  289,  316,  339,  315,  319,
      338,  340,  345,  341,  355,  314,  346,  353,  338,  318,
      345,  319,  346,  339,  354,  358,  353,  363,  355,  366,
      368,  367,  354,  340,  341,  367,  370,  371,  368,  373,
      374,  383,  394,  389,  360,  389,  373,  389,  374,  395,
      359,  395,  356,  395,  366,  370,  352,  363,  371,  358,
      383,  351,  350,  349,  348,  389,  347,  344,  394,  343,

      342,  395,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  405,  405,  337,  405,  405,
      405,  405,  405,  405,  405,  405,  406,  406,  328,  327,
      406,  406,  407,  407,  407,  325,  407,  407,  407,  407,
      407,  407,  407,  408,  324,  408,  408,  408,  408,  408,
      321,  408,  408,  408,  409,  409,  320,  317,  409,  310,
      305,  409,  300,  409,  410,  410,  299,  296,  410,  291,
      290,  410,  281,  410,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  412,  412,  412,  413,  413,
      414,  414,  415,  415,  416,  416,  417,  417,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  419,
      419,  420,  420,  421,  421,  422,  422,  423,  423,  424,
      424,  425,  425,  426,  426,  427,  427,  428,  428,  429,
      429,  430,  430,  431,  431,  432,  432,  433,  433,  434,
      434,  435,  435,  436,  436,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  439,  439,  440,
      440,  441,  441,  442,  442,  443,  443,  444,  444,  445,

      445,  446,  446,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  448,  448,  449,  449,  450,  450,
      451,  451,  452,  452,  453,  453,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  455,  455,  456,
      456,  457,  457,  458,  458,  459,  459,  460,  460,  461,
      461,  462,  462,  463,  463,  464,  464,  280,  279,  278,
      273,  270,  257,  255,  252,  251,  246,  245,  243,  220,
      218,  217,  216,  215,  210,  209,  192,  189,  170,  169,
      164,  163,  157,  148,  147,  146,  145,  144,  143,  136,
      135,  120,   98,   97,   96,   89,   82,   79,   72,   71,

       70,   68,   58,   57,   56,   35,   32,   29,   26,   18,
       16,   11,    7,    2,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[71] =
    {   0,
0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c_cross.l"


/* 通用字符名 */
/* 浮点数指数部分 */
/* 整数长度 */
#line 14 "c_cross.l"
	/* 符号表 */
	struct symbol {
		struct ref *reflist;
		char *name;
	};
	
	struct ref {
		struct ref *next;
		char *filename;
		int flags;
		int lineno;
	};
	
	#define NHASH 9997
	struct symbol symtab[NHASH];          // 哈希表，线性探测
	struct symbol *lookup(char*);         // 查找符号 
	void addref(int, char*, char*, int);  // 将 ref 添加到对应符号表
	char *curfilename;
	
	/* 文件堆栈 */
	struct bufstack {
		struct bufstack *prev;
		YY_BUFFER_STATE bs;
		int lineno;
		char *filename;
		FILE *f;
	} *curbs;
	
	int newfile(char *fn);
	int popfile(void);
	int defining;
#line 906 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define IFILE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 47 "c_cross.l"


 /* 注释 */
#line 1102 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 402 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1015 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "c_cross.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "c_cross.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 52 "c_cross.l"
{ /* ignore */ }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 53 "c_cross.l"
{ printf("%s:%d: Unterminated comment\n", curfilename, yylineno); return 0; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 54 "c_cross.l"

	YY_BREAK
/* 声明关键字 */
case 5:
#line 58 "c_cross.l"
case 6:
#line 59 "c_cross.l"
case 7:
#line 60 "c_cross.l"
case 8:
#line 61 "c_cross.l"
case 9:
#line 62 "c_cross.l"
case 10:
#line 63 "c_cross.l"
case 11:
#line 64 "c_cross.l"
case 12:
#line 65 "c_cross.l"
case 13:
#line 66 "c_cross.l"
case 14:
#line 67 "c_cross.l"
case 15:
#line 68 "c_cross.l"
case 16:
#line 69 "c_cross.l"
case 17:
#line 70 "c_cross.l"
case 18:
#line 71 "c_cross.l"
case 19:
#line 72 "c_cross.l"
case 20:
#line 73 "c_cross.l"
case 21:
#line 74 "c_cross.l"
case 22:
#line 75 "c_cross.l"
case 23:
#line 76 "c_cross.l"
case 24:
#line 77 "c_cross.l"
case 25:
#line 78 "c_cross.l"
case 26:
#line 79 "c_cross.l"
case 27:
#line 80 "c_cross.l"
case 28:
YY_RULE_SETUP
#line 80 "c_cross.l"
{ defining = 1; }
	YY_BREAK
/* 关键字 */
case 29:
YY_RULE_SETUP
#line 83 "c_cross.l"

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "c_cross.l"

	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "c_cross.l"

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "c_cross.l"

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "c_cross.l"

	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "c_cross.l"

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "c_cross.l"

	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "c_cross.l"

	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "c_cross.l"

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "c_cross.l"

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "c_cross.l"

	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "c_cross.l"

	YY_BREAK
case 41:
YY_RULE_SETUP
#line 95 "c_cross.l"

	YY_BREAK
/* 整数 */
case 42:
YY_RULE_SETUP
#line 98 "c_cross.l"

	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "c_cross.l"

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "c_cross.l"

	YY_BREAK
/* 十进制浮点数 */
case 45:
YY_RULE_SETUP
#line 103 "c_cross.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "c_cross.l"

	YY_BREAK
/* 十六进制浮点数 */
case 47:
YY_RULE_SETUP
#line 106 "c_cross.l"

	YY_BREAK
/* 字符常量 */
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 109 "c_cross.l"

	YY_BREAK
/* 字符串常量 */
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 111 "c_cross.l"

	YY_BREAK
/* 标点符号 */
case 50:
YY_RULE_SETUP
#line 114 "c_cross.l"
{ defining = 0; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "c_cross.l"

	YY_BREAK
case 52:
YY_RULE_SETUP
#line 116 "c_cross.l"

	YY_BREAK
case 53:
YY_RULE_SETUP
#line 117 "c_cross.l"

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 118 "c_cross.l"

	YY_BREAK
case 55:
YY_RULE_SETUP
#line 119 "c_cross.l"

	YY_BREAK
case 56:
YY_RULE_SETUP
#line 120 "c_cross.l"

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 121 "c_cross.l"

	YY_BREAK
/* 标识符 */
case 58:
YY_RULE_SETUP
#line 124 "c_cross.l"
{ addref(yylineno, curfilename, yytext, defining); }
	YY_BREAK
/* 空白字符 */
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 127 "c_cross.l"

	YY_BREAK
/* 续行符 */
case 60:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 130 "c_cross.l"

	YY_BREAK
/* 预处理器 */
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 133 "c_cross.l"

	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 134 "c_cross.l"

	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 135 "c_cross.l"

	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 136 "c_cross.l"

	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 137 "c_cross.l"

	YY_BREAK
/* 识别包含文件 */
case 66:
YY_RULE_SETUP
#line 140 "c_cross.l"
{ BEGIN IFILE; }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 141 "c_cross.l"
{
									{
										int c;
										while ((c=input()) && c!='\n');
									}
									newfile(strdup(yytext));
									BEGIN INITIAL;
								}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 149 "c_cross.l"
{
									fprintf(stderr, "%s:%d bad include line\n", curfilename, yylineno);
									BEGIN INITIAL;
								}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 153 "c_cross.l"
{
									if (!popfile())
										yyterminate();
								}
	YY_BREAK
/* 无效字符 */
case 69:
YY_RULE_SETUP
#line 159 "c_cross.l"
{
									printf("%s:%d: Mystery character '%s'\n", curfilename, yylineno, yytext);
								}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 163 "c_cross.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1530 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 402 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 402 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 401);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 163 "c_cross.l"



// 
static int symcompare(const void *xa, const void *xb)
{
	const struct symbol *a = xa;
	const struct symbol *b = xb;
	if (!a->name) {
		if (!b->name)
			return 0;
		return 1;
	}
	if (!b->name)
		return -1;
	return strcmp(a->name, b->name);
}

void printrefs()
{
	struct symbol *sp;
	qsort(symtab, NHASH, sizeof(struct symbol), symcompare);
	
	for (sp=symtab; sp->name && sp < symtab+NHASH; sp++) {
		char *prevfn = NULL;
		
		struct ref *rp = sp->reflist;
		struct ref *rpp = 0;
		struct ref *rpn;
		
		do {
			rpn = rp->next;
			rp->next = rpp;
			rpp = rp;
			rp = rpn;
		} while(rp);
		
		printf("%10s", sp->name);
		for (rp=rpp; rp; rp=rp->next) {
			if (rp->filename==prevfn) {
				printf(" %d", rp->lineno);
			} else {
				printf(" %s:%d", rp->filename, rp->lineno);
				prevfn = rp->filename;
			}
			if (rp->flags & 01)
				printf("*");
		}
		printf("\n");
	}
}

static unsigned symhash(char *sym)
{
	unsigned int hash = 0;
	unsigned c;
	while (c = *sym++)
		hash = hash * 9 ^ c;
	return hash;
}

struct symbol * lookup(char *sym)
{
	struct symbol *sp = &symtab[symhash(sym)%NHASH];
	int scount = NHASH;
	
	while (--scount >= 0) {
		if (sp->name && !strcmp(sp->name, sym))
			return sp;
			
		if (!sp->name) {
			sp->name = strdup(sym);
			sp->reflist = 0;
			return sp;
		}
		
		if (++sp >= symtab+NHASH)
			sp = symtab;
	}
	fputs("symbol table overflow\n", stderr);
	abort();
}

void addref(int lineno, char *filename, char *word, int flags)
{
	struct ref *r;
	struct symbol *sp = lookup(word);
	
	if (sp->reflist &&
		sp->reflist->lineno == lineno &&
		sp->reflist->filename == filename)
		return;
		
	r = malloc(sizeof(struct ref));
	if (!r) {
		fputs("out of space\n", stderr);
		abort();
	}
	r->next = sp->reflist;
	r->filename = filename;
	r->lineno = lineno;
	r->flags = flags;
	sp->reflist = r;
}

int main(int argc, char **argv)
{
	int i;
	
	if (argc < 2) {
		fprintf(stderr, "need filename\n");
		return 1;
	}
	for (i = 1; i < argc; i++) {
		if (newfile(argv[i]))
			yylex();
	}
	printrefs();
	return 0;
}

int newfile(char *fn)
{
	FILE *f = fopen(fn, "r");
	struct bufstack *bs = malloc(sizeof(struct bufstack));
	
	if (!f) {
		perror(fn);
		return 0;
	}
	if (!bs) {
		perror("malloc");
		exit(1);
	}
	if (curbs)
		curbs->lineno = yylineno;
	bs->prev = curbs;
	
	bs->bs = yy_create_buffer(f,YY_BUF_SIZE);
	bs->f = f;
	bs->filename = fn;
	yy_switch_to_buffer(bs->bs);
	curbs = bs;
	yylineno = 1;
	curfilename = fn;
	return 1;
}

int popfile(void)
{
	struct bufstack *bs = curbs;
	struct bufstack *prevbs;
	
	if (!bs)
		return 0;
		
	fclose(bs->f);
	yy_delete_buffer(bs->bs);
	
	prevbs = bs->prev;
	free(bs);
	
	if (!prevbs)
		return 0;
		
	yy_switch_to_buffer(prevbs->bs);
	curbs = prevbs;
	yylineno = curbs->lineno;
	curfilename = curbs->filename;
	return 1;
}

